<?php
/**
* 2007-2016 PrestaShop
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@prestashop.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please refer to http://www.prestashop.com for more information.
*
*  @author    PrestaShop SA <contact@prestashop.com>
*  @copyright 2007-2016 PrestaShop SA
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*/

class SampleDataSlider
{
	public function initData()
	{
		$return = true;
		$languages = Language::getLanguages(true);
		$id_shop = Configuration::get('PS_SHOP_DEFAULT');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow` (`id_wtslideshow`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, 0, 4000, \'["1"]\', "false", 0, 1),
		(2, 0, 4000, \'["2"]\', "false", 0, 1),
		(3, 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_shop` (`id_wtslideshow`, `id_shop`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, "'.$id_shop.'", 0, 4000, \'["1"]\', "false", 0, 1),
		(2, "'.$id_shop.'", 0, 4000, \'["2"]\', "false", 0, 1),
		(3, "'.$id_shop.'", 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options` (`id_wtslideshow_op`, `options`) VALUES 
		(1, \'{"fullwidth":"true","width":"1920","height":"905","responsive":"true","responsiveUnder":"1920","layersContainer":"1920","showmobile":"true","autoStart":"true","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\\/css\\/skins\\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"true","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\');');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options_shop` (`id_wtslideshow_op`, `id_shop`, `options`) VALUES 
		(1, "'.$id_shop.'", \'{"fullwidth":"true","width":"1920","height":"905","responsive":"true","responsiveUnder":"1920","layersContainer":"1920","showmobile":"true","autoStart":"true","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\\/css\\/skins\\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"true","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\')
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption` (`id_caption`, `id_wtslideshow`, `type`, `order`, `params`) VALUES 
		(53, 1, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(56, 2, 1, 600, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"574","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(57, 2, 1, 900, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"804","datay":"533","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(58, 2, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(61, 3, 1, 600, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"584","datay":"314","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(62, 3, 1, 900, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"790","datay":"534","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(63, 3, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(66, 1, 1, 900, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"570","datay":"311","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(67, 1, 1, 1200, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"851","datay":"504","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(72, 1, 2, 1200, \'{"style":"big_black","parallaxlevel":"1","class":"","datax":"842","datay":"410","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(73, 1, 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"781","datay":"569","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(74, 1, 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"818","datay":"604","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(75, 2, 2, 1200, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"842","datay":"427","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(76, 2, 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"835","datay":"601","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(77, 2, 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"724","datay":"634","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(78, 3, 2, 1500, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"828","datay":"434","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(79, 3, 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"810","datay":"606","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(80, 3, 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"700","datay":"638","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_shop` (`id_caption`, `id_wtslideshow`, `id_shop`, `type`, `order`, `params`) VALUES 
		(53, 1, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(56, 2, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"574","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(57, 2, "'.$id_shop.'", 1, 900, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"804","datay":"533","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(58, 2, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(61, 3, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"584","datay":"314","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(62, 3, "'.$id_shop.'", 1, 900, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"790","datay":"534","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(63, 3, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"775","datay":"255","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(66, 1, "'.$id_shop.'", 1, 900, \'{"style":"very_big_white","parallaxlevel":"1","class":"","datax":"570","datay":"311","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(67, 1, "'.$id_shop.'", 1, 1200, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"851","datay":"504","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(72, 1, "'.$id_shop.'", 2, 1200, \'{"style":"big_black","parallaxlevel":"1","class":"","datax":"842","datay":"410","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(73, 1, "'.$id_shop.'", 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"781","datay":"569","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(74, 1, "'.$id_shop.'", 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"818","datay":"604","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(75, 2, "'.$id_shop.'", 2, 1200, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"842","datay":"427","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(76, 2, "'.$id_shop.'", 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"835","datay":"601","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(77, 2, "'.$id_shop.'", 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"724","datay":"634","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(78, 3, "'.$id_shop.'", 2, 1500, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"828","datay":"434","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(79, 3, "'.$id_shop.'", 1, 1500, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"810","datay":"606","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(80, 3, "'.$id_shop.'", 1, 1800, \'{"style":"grassfloor","parallaxlevel":"0","class":"","datax":"700","datay":"638","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1800","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		foreach ($languages as $language)
		{
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_lang` (`id_wtslideshow`, `id_lang`, `id_shop`, `title`, `url`, `image`, `thumbnail`) VALUES 
			(1, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "63c055b2ec9ca2a31f126ba31ccf0a252167dcdb_slider-1.jpg", ""),
			(2, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "34238461d8f400ad3d65290d4d3ac045268a5af5_slider-2.jpg", ""),
			(3, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "b2342e820bec4f39c1058b65e7cb3aa5ed57fbdb_slider-3.jpg", "");
			');
			
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_lang` (`id_caption`, `id_shop`, `id_lang`, `captext`, `capimage`, `capvideo`, `link`) VALUES
			(53, "'.$id_shop.'", "'.$language['id_lang'].'", "Welcome to Delicious", "Layer Image 3", "Layer Video 3", "#"),
			(56, "'.$id_shop.'", "'.$language['id_lang'].'", "Bell Chalupa", "Layer Image 1", "Layer Video 1", "#"),
			(57, "'.$id_shop.'", "'.$language['id_lang'].'", "aliquam sem facilisis", "Layer Image 2", "Layer Video 2", "#"),
			(58, "'.$id_shop.'", "'.$language['id_lang'].'", "Donec convallis felis ", "Layer Image 3", "Layer Video 3", "#"),
			(61, "'.$id_shop.'", "'.$language['id_lang'].'", "Bell Chalupa", "Layer Image 1", "Layer Video 1", "#"),
			(62, "'.$id_shop.'", "'.$language['id_lang'].'", "aliquam sem facilisis", "Layer Image 2", "Layer Video 2", "#"),
			(63, "'.$id_shop.'", "'.$language['id_lang'].'", "Donec convallis felis ", "Layer Image 3", "Layer Video 3", "#"),
			(66, "'.$id_shop.'", "'.$language['id_lang'].'", "specical menu", "Layer Image 2", "Layer Video 2", "#"),
			(67, "'.$id_shop.'", "'.$language['id_lang'].'", "openning hours", "Layer Image 3", "Layer Video 3", "#"),
			(72, "'.$id_shop.'", "'.$language['id_lang'].'", "Image 3", "1fc066b54c7f1860f4699cbcb11e50033aede410_caption_slider.png", "", "#"),
			(73, "'.$id_shop.'", "'.$language['id_lang'].'", "Monday - Friday: 09:00 A.M - 23:00 P.M", "Layer Image 4", "Layer Video 4", "#"),
			(74, "'.$id_shop.'", "'.$language['id_lang'].'", "Weekend: 09:00 A.M - 3:00 P.M", "Layer Image 5", "Layer Video 5", "#"),
			(75, "'.$id_shop.'", "'.$language['id_lang'].'", "Image 3", "1fc066b54c7f1860f4699cbcb11e50033aede410_caption_slider.png", "", "#"),
			(76, "'.$id_shop.'", "'.$language['id_lang'].'", "Morbi vel eros augue Donec", "Layer Image 4", "Layer Video 4", "#"),
			(77, "'.$id_shop.'", "'.$language['id_lang'].'", "felis diam efficitur ultrices euismod placerat sodales", "Layer Image 5", "Layer Video 5", "#"),
			(78, "'.$id_shop.'", "'.$language['id_lang'].'", "Image 4", "1fc066b54c7f1860f4699cbcb11e50033aede410_caption_slider.png", "", "#"),
			(79, "'.$id_shop.'", "'.$language['id_lang'].'", "Morbi vel eros augue Donec", "Layer Image 4", "Layer Video 4", "#"),
			(80, "'.$id_shop.'", "'.$language['id_lang'].'", "felis diam efficitur ultrices euismod placerat sodales", "Layer Image 5", "Layer Video 5", "#");');
		}
		return $return;
	}
}
?>